name: bonobo
dependencies:
  angel_serialize: ^2.0.0
  args: ^1.0.0
  c_builder: ^1.0.0
  dart_language_server: ^0.1.9
  file: ^2.0.0
  resource: ^2.0.0
  string_scanner: ^1.0.0
  source_span: ^1.0.0
  symbol_table: ^1.0.0
  tuple: ^1.0.0
  scanner:
    path: ../scanner
  parser:
    path: ../parser
  ast:
    path: ../ast
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^0.8.0
  test: ^0.12.0
executables:
  bonobo: bonobo