name: parser
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  scanner:
    path: ../scanner
  source_span: ^1.0.0
  ast:
    path: ../ast

dev_dependencies:
  test: ^0.12.0
